NOTABI1=float(input("DIGITE A NOTA DO 1º BIMESTRE: "))
NOTABI2=float(input("DIGITE A NOTA DO 2º BIMESTRE: "))
NOTABI3=float(input("DIGITE A NOTA DO 3º BIMESTRE: "))
NOTABI4=float(input("DIGITE A NOTA DO 4º BIMESTRE: "))
MEDIA=(NOTABI1+NOTABI2+NOTABI3+NOTABI4)/4
print("A MÉDIA BIMESTRAL É: ",MEDIA)